pool:
  vmImage: 'ubuntu-latest'
trigger:
  - develop
variables:
  frontImageNameAndTag: '$(baseImageName)-front:$(env)'
jobs:
  - job: Front
    variables:
      - group: 'tpfinal-vars'
    steps:
      - template: ./templates/_build-front.yml
      - script: echo $(containerRegistryPassword) | docker login -u $(containerRegistry) --password-stdin $(containerRegistry).azurecr.io
        displayName: "Docker login"
      - script: docker build -t $(containerRegistry).azurecr.io/$(frontImageNameAndTag) -f $(frontProjectPath)/Dockerfile $(frontProjectPath)
        displayName: "Docker build $(frontImageNameAndTag)"
      - script: docker push $(containerRegistry).azurecr.io/$(frontImageNameAndTag)
        displayName: "Docker push $(frontImageNameAndTag)"